export const listEmployees = [
    {
        id: 0,
        img: "",
        name: "Lê Duy Tường",
        role: "Admin",
        department: "Test",
        contactInf: {
            email: "duytuong100101@gmail.com",
            phone: "0964088473",
        },
        statusEmployee: 1,
        statusUsingHappyTime: 1,
    },
    {
        id: 1,
        img: "",
        name: "Nguyễn Thiên Hoàn",
        role: "Quản lý",
        department: "Test",
        contactInf: {
            email: "duytuong100101@gmail.com",
            phone: "0964088473",
        },
        statusEmployee: 1,
        statusUsingHappyTime: 1,
    },
    {
        id: 2,
        img: "",
        name: "Nguyễn Tấn Đạt",
        role: "Nhân viên",
        department: "Test",
        contactInf: {
            email: "tandatdeptrairattretrau@gmail.com",
            phone: "0964088473",
        },
        statusEmployee: 1,
        statusUsingHappyTime: 1,
    },
    {
        id: 3,
        img: "",
        name: "Lê Duy Tường",
        role: "Nhân viên",
        department: "Test",
        contactInf: {
            email: "duytuong100101@gmail.com",
            phone: "0964088473",
        },
        statusEmployee: 1,
        statusUsingHappyTime: 1,
    },
    {
        id: 4,
        img: "",
        name: "Lê Duy Tường",
        role: "Nhân viên",
        department: "Test",
        contactInf: {
            email: "duytuong100101@gmail.com",
            phone: "0964088473",
        },
        statusEmployee: 1,
        statusUsingHappyTime: 1,
    },
    {
        id: 5,
        img: "",
        name: "Lê Duy Tường",
        role: "Nhân viên",
        department: "Test",
        contactInf: {
            email: "duytuong100101@gmail.com",
            phone: "0964088473",
        },
        statusEmployee: 1,
        statusUsingHappyTime: 1,
    },
];
