export const listEmployees = [
    {
        key: 0,
        id: "0",
        img: "",
        name: "Lê Duy Tường",
        role: "Quản lý",
        department: "Coffee Store",
        totalLeave: {
            total: 0,
            used: 0,
            expire: 0,
            rest: 0,
        },
        theLeaveThisYear: {
            total: 0,
            used: 0,
            rest: 0,
        },
        theLeaveLastYear: {
            total: 0,
            used: 0,
            expire: 0,
            rest: 0,
        },
    },
    {
        key: 1,
        id: "0",
        img: "",
        name: "Lê Duy Tường",
        role: "Quản lý",
        department: "Coffee Store",
        totalLeave: {
            total: 0,
            used: 0,
            expire: 0,
            rest: 0,
        },
        theLeaveThisYear: {
            total: 0,
            used: 0,
            rest: 0,
        },
        theLeaveLastYear: {
            total: 0,
            used: 0,
            expire: 0,
            rest: 0,
        },
    },
    {
        key: 2,
        id: "0",
        img: "",
        name: "Lê Duy Tường",
        role: "Quản lý",
        department: "Coffee Store",
        totalLeave: {
            total: 0,
            used: 0,
            expire: 0,
            rest: 0,
        },
        theLeaveThisYear: {
            total: 0,
            used: 0,
            rest: 0,
        },
        theLeaveLastYear: {
            total: 0,
            used: 0,
            expire: 0,
            rest: 0,
        },
    },

    {
        key: 3,
        id: "0",
        img: "",
        name: "Lê Duy Tường",
        role: "Quản lý",
        department: "Coffee Store",
        totalLeave: {
            total: 0,
            used: 0,
            expire: 0,
            rest: 0,
        },
        theLeaveThisYear: {
            total: 0,
            used: 0,
            rest: 0,
        },
        theLeaveLastYear: {
            total: 0,
            used: 0,
            expire: 0,
            rest: 0,
        },
    },
    {
        key: 4,
        id: "0",
        img: "",
        name: "Lê Duy Tường",
        role: "Quản lý",
        department: "Coffee Store",
        totalLeave: {
            total: 0,
            used: 0,
            expire: 0,
            rest: 0,
        },
        theLeaveThisYear: {
            total: 0,
            used: 0,
            rest: 0,
        },
        theLeaveLastYear: {
            total: 0,
            used: 0,
            expire: 0,
            rest: 0,
        },
    },
];
