import { Employee } from "store/slices/Main/Employees/employeesSlice";

export const CreateDefaultValues: Employee = {
  _id: "",
  name: "",
  username: "",
  avatar: "",
  identify_id: "",
  staying_address: "",
  phone_number: "",
  company_mail: "",
  issued_by: "",
  residence_address: "",
  school_name: "",
  personal_mail: "",
  personal_tax_id: "",
  major: "",
  bank_account_number: "",
  bank: "",
  bank_branch: "",
  working_branch: "",
  note: "",
  agent_code: "",
  date_of_birth: 0,
  device_id: "",
  is_used_happy_time: false,
  stop_working_date: 0,
  tenant_id: "",
  graduation_date: 0,
  gender: "",
  married_status: "",
  education_type: "",
  issued_date: 0,
  start_working_date: 0,
  agent_status: "",
  agent_type: "",
  role: "",
  agent_position: "",
  department: "",
  company_name: "",
};
